### ISSUE TITLE
Improve usability of imports in the `curve25519-dalek` API

### ISSUE THREAD

**Issue by rubdos** [dalek-cryptography/curve25519-dalek#111]
Hi!

Thanks for this clean library. I like this so far.

One thing I am wondering about:

```rust
use curve25519_dalek::{constants, edwards, scalar};
// [snip]
struct Foo {
    r: scalar::Scalar,
    p: edwards::EdwardsPoint,
}
```

since most (all?) structs basically have their module name in their own name (edwards -> EdwardsPoint, scalar -> Scalar, ...), would it make sense to make some sort of `prelude` module, such that I could do

```rust
use curve25519_dalek::edwards::prelude::*;
// [snip]
struct Foo {
    s: Scalar,
    p: EdwardsPoint,
}
```

? `prelude` can import from the `scalar` and `edwards` modules.

Just searching for a way to reduce this kind of duplication a bit. What do you guys think?

**Comment by tarcieri** [comment]
I'm not sure how much this qualifies as idiomatic Rust, but my personal preferred way to handle this is by re-exporting module-specific types out of the crate's `lib.rs` (i.e. `pub use edwards::EdwardsPoint`) so you-as-a-user could just do:

```rust
use curve25519_dalek::{EdwardsPoint, Scalar};
```

I believe there were some style suggestions to do something like `edwards::Point` instead of `EdwardsPoint` originally, but I have found that approach to be somewhat unworkable when you have several modules that contain types with the same name, which if they ever interact you have to do nonsense like `use edwards::Point as EdwardsPoint` anyway at which point why not just name the damn thing `EdwardsPoint` to begin with.

**Comment by rubdos** [comment]
> I believe there were some style suggestions to do something like edwards::Point instead of EdwardsPoint originally

Wouldn't agree with that either. Let's say you use both montgomery and edwards for some reason, that won't be nice to deal with.

Exporting them out of the root works too for me.

**Comment by hdevalence** [comment]
Thanks for the feedback! I don't have super strong opinions about making a prelude or about re-exporting types from the root, but it's something we should figure out before stabilizing the API.

It is kind of awkward that most of the modules just have one type. I guess for the `edwards` and `ristretto` modules there's also the multiscalar functions, although maybe in the future we could express those as traits.  (So far there's not a `Group` trait or similar mostly because a) no const generics make it difficult to write generic serialization code and b) because we just have two groups so far, and they're not really interchangeable.)

I guess the intended import pattern was something like
```
use curve25519_dalek::constants;
use curve25519_dalek::edwards::EdwardsPoint;
use curve25519_dalek::scalar::Scalar;

// [snip]
struct Foo {
    r: Scalar,
    P: EdwardsPoint,
}
```
which is a little more verbose up-front but makes the code nicer. At that point it's maybe worth providing a `prelude` module that contains all of the types, although I think it's nice to be explicit about what parts are in use -- for instance, the above code clearly doesn't use any Montgomery arithmetic.

**Comment by tarcieri** [comment]
> It is kind of awkward that most of the modules just have one type. 

I think this is great from an implementer's perspective, but an implementation detail to the end-user.

> I guess the intended import pattern was something like...

The equivalent with re-exported types would be:

```
use curve25519_dalek::{constants, EdwardsPoint, Scalar};
```

>  I think it's nice to be explicit about what parts are in use

I do too! The above is just as explicit but less redundant

**Comment by hdevalence** [comment]
Hi there, I think we're going to keep the module structure mostly as-is. It's a little awkward to import things sometimes, but the upshot is that all of the types are pretty clearly organized within the public API.
