### ISSUE TITLE
Does not compile with --no-default-features

### ISSUE THREAD

**Issue by doomrobo** [dalek-cryptography/curve25519-dalek#156]
I tried to compile without default features because I was getting a dependency conflict with `rand`, but there were pages and pages of compile errors.

Not compiling with `u64_backend` gives a ton of errors relating to missing constants. Not compiling with `std` gives a ton of errors relating to `Vec` and other stuff imported by default in `std`.

**Comment by hdevalence** [comment]
We should document this better: when compiling with `--no-default-features`, you have to specify which backend you want to use. So, for instance, to build in `no_std`, you would use `--no-default-features --features "u64_backend"`.

Are the `rand` errors caused by trying to use `rand = 0.4` in the parent crate, while `curve25519-dalek` uses `rand = 0.5`?

**Comment by doomrobo** [comment]
Ah, here was the issue: I was doing `cargo test --no-default-features --features "u64_backend"` which does fail, but only because the tests require some `std` stuff. `cargo build` with those flags works just fine.

Sorry for the bother.

**Comment by hdevalence** [comment]
No worries! Changes to the docs on this point are in https://github.com/dalek-cryptography/curve25519-dalek/pull/155/commits/fa904c2c420a1909044ef40b90cdde0913c1051f
