### ISSUE TITLE
C bindings?

### ISSUE THREAD

**Issue by Scratch-net** [dalek-cryptography/curve25519-dalek#182]
Ristretto is a great replacement for P-256 and it would be super cool to be able to use it in C which would automatically expand it to Go/C#/Java, even JS.
There are some password protecting protocols like [Sphinx](http://webee.technion.ac.il/~hugo/sphinx.pdf) or the new PHE that would benefit from moving to 25519 instead of NIST.

Would you consider adding build instructions or standard bindings for languages other than Rust?

**Comment by tarcieri** [comment]
This might be helpful: https://github.com/eqrion/cbindgen

**Comment by Scratch-net** [comment]
Ok, will try but it's good when authors consider official bindings

**Comment by hdevalence** [comment]
Unfortunately we have no plans to add C bindings to `curve25519-dalek`, because we use a lot of Rust features to provide a safe API. For instance, because Rust has definite initialization, we can ensure that all points are valid curve points at all times -- so unlike libsodium, we don't have a function to check whether a point is valid, because it's not possible in safe Rust to create an invalid `RistrettoPoint`.

Rather than provide C bindings to the mid-level API in `curve25519-dalek`, our suggestion is that protocols/primitives should be implemented in Rust using `curve25519-dalek` as a dependency, and those crates can provide minimal, buffer-oriented C APIs that are specific to the protocol/primitive.

**Comment by Scratch-net** [comment]
Ok, so the idea is to (for example) implement protocol and export only those couple of methods that deal with bytes

**Comment by hdevalence** [comment]
Yeah, we should probably add this to the docs somewhere -- I'm going to reopen this issue, and close it when the docs are updated to note this

**Comment by hdevalence** [comment]
Closing this now that #183 is merged.
