### ISSUE TITLE
How do i generate an ecdsa signature for a Ristretto point?

### ISSUE THREAD

**Issue by Dylan-Phoon** [dalek-cryptography/curve25519-dalek#212]
Is there any api for this?

More specifically, for generating a signature for two commits that are implemented on `PedersenGens` in the bulletproofs library;
e.g. (a.H + x.G) - (a.H + y.G) == (x-y)G //get signature for x-y

**Comment by hdevalence** [comment]
We don't have any API for that, but you could, in theory, use this library to implement your own protocols -- it's not supposed to provide any constructions on its own. However the construction you're describing doesn't seem to be secure, since reusing the blinding factors means the commitments aren't hiding the values any more...
