### ISSUE TITLE
Is `RistrettoPoint::compress` a constant time operation

### ISSUE THREAD

**Issue by HeroicKatora** [dalek-cryptography/curve25519-dalek#246]
The implementation certainly looks like it should be a constant time operation. If so, I did not find it mentioned in the documentation, whereas it is explicitely mentioned for Scalar multiplication for example. The only high-level explanation that makes it possible to follow [is the encoding description on https://ristretto.group](https://ristretto.group/formulas/encoding.html) which is not constant time.

The [test thread in subtle](https://github.com/dalek-cryptography/subtle/pull/22#issuecomment-441471356) about constant time testing is also sparse with details on *which* operations were tested.

**Comment by hdevalence** [comment]
Yes, the implementation is constant-time, although this isn't mentioned in the documentation because in order for something to be constant-time, it needs to be constant with respect to some secret data, and usually a point is not considered secret.

The encoding description on the Ristretto website is not written to be constant-time, as you mention, just because it's aiming at clarity -- it's not much work to write it as a constant-time procedure, and the description in the [Internet-Draft](https://datatracker.ietf.org/doc/draft-hdevalence-cfrg-ristretto/?include_text=1) does so.
