### ISSUE TITLE
Ristretto: half of 8-torsion points map to a different ristretto point than the other half

### ISSUE THREAD

**Issue by valerini** [dalek-cryptography/curve25519-dalek#312]
For ristretto in curve25519-dalek two torsion points (one of order 4 and another of order 8) map to different ristretto points, so the following code fails:
```
assert_eq!(RistrettoPoint(constants::EIGHT_TORSION[1]),
                   RistrettoPoint(constants::EIGHT_TORSION[2]));
```
this also fails:
```
let bp = constants::RISTRETTO_BASEPOINT_POINT;
assert_eq!(bp, RistrettoPoint(bp.0 + constants::EIGHT_TORSION[1]));
```

while this code succeeds:
```
assert_eq!(bp, RistrettoPoint(bp.0 + constants::EIGHT_TORSION[2]));
```

Is this behavior intended?

I was expecting Ristretto group to help get rid of the 8-torsion component completely, but this seems to only be getting rid of half of it as the even points of 8-torsion are mapped to one thing, while the odd points of 8-torsion are mapped to another thing. Most likely I am just missing something basic here, if you could clarify this behavior, this would be of tremendous help! Thank you!

**Comment by hdevalence** [comment]
Yes, this is intended.  I think the root problem that led to your expectation being surprised is that Ristretto does not construct a prime-order group as `E/E[8]` (all points on `E`, mod 8-torsion points), but as `[2]E/E[8]` (even points on `E`, mod 4-torsion points).  This is explained in more detail on the [Encoding with Isogenies](https://ristretto.group/details/isogeny_encoding.html) and [Conceptual Diagram](https://ristretto.group/details/conceptual_diagram.html) pages of the Ristretto website, but the effect is that not every point on the Edwards curve represents a Ristretto point.  Only some Edwards points are valid representatives, which is why the `RistrettoPoint` tuple struct makes the inner representative `pub(crate)`, so that it's not possible for library users to construct invalid points.

Does this help?

**Comment by valerini** [comment]
Great, thank you so much for such a quick response! This makes a lot of sense now.

But then I have the following question: if I receive bytes over the wire (from an untrusted source), how should I verify if they give a ristretto point of prime-order? For example if I receive a point R, multiply it by my secret random scalar s and send back s * R, I need to be sure R is a prime-order point. How to do it with ristretto then? It seems then I can be tricked into operating with R that has a 2-torsion component, like this one `R = RistrettoPoint(constants::EIGHT_TORSION[1]) + constants::RISTRETTO_BASEPOINT_POINT`.

**Comment by hdevalence** [comment]
When you get bytes over the wire (say a `my_bytes: [u8; 32]`), you mark them as representing a compressed Ristretto point using the `CompressedRistretto` type, and then call `decompress`: `CompressedRistretto(my_bytes).decompress()`. This gives an `Option<RistrettoPoint>`, which is either `Some(RistrettoPoint)` (if the bytes were the canonical encoding of a Ristretto point) or `None` (if they weren't).

There's no way for you as a library user to construct a `RistrettoPoint` with an invalid internal representation as in your example, because the inner element of the tuple struct is `pub(crate)`, so it's only accessible inside `curve25519-dalek` itself, so your example won't compile unless you're modifying the library itself.

**Comment by valerini** [comment]
I see, beautiful, thank you so much!

**Comment by valerini** [comment]
Hi Henry,

Your explanations were so helpful, may I ask one more question (hoping not to take advantage of your time): what Edwards points would map to valid Ristretto points, is there a simple description of this set?

In particular, I am trying to understand why BASE_POINT maps to a valid ristretto point and BASE_POINT + EIGHT_TORSION_POINT maps to a valid ristretto point. As an example, this test passes:

```
assert_eq!(true, CompressedRistretto(*(RistrettoPoint(constants::ED25519_BASEPOINT_POINT)).compress().as_bytes()).decompress().is_some());

assert_eq!(true, CompressedRistretto(*(RistrettoPoint(constants::ED25519_BASEPOINT_POINT + constants::EIGHT_TORSION[1])).compress().as_bytes()).decompress().is_some());

assert_eq!(false, CompressedRistretto(*(RistrettoPoint(constants::EIGHT_TORSION[1])).compress().as_bytes()).decompress().is_some());
```

**Comment by tarcieri** [comment]
There is presently no well-defined map between Edwards and Ristretto points

**Comment by hdevalence** [comment]
@valerini The simplest description of the Edwards points that can represent Ristretto points is `[2]E/E[4]`, i.e., the "even" points `[2]E` (the image of the multiplication-by-two map `[2]`), mod the 4-torsion points `E[4]`. However, there are multiple possible internal representations for Ristretto, depending on which curve is used internally, and the functions are designed so that different implementations can use different curves internally without breaking compatibility.  That's why there's no map defined between Edwards and Ristretto points, as @tarcieri mentions.

**Comment by valerini** [comment]
So if I understood correctly, you were saying, the compression will be well defined for points in 2E (this includes E[4], I believe) and might not be well defined for the rest of the points (for E \ 2E).

Thanks for your answers! I think now it all came together to a coherent picture for me.
