### ISSUE TITLE
Point with different representation

### ISSUE THREAD

**Issue by Fiono11** [dalek-cryptography/curve25519-dalek#317]
Hello! I have the following snippet of code:

```rust 
use curve25519_dalek::constants::RISTRETTO_BASEPOINT_POINT;
use curve25519_dalek::scalar::Scalar;
use curve25519_dalek::ristretto::RistrettoPoint;

fn main() {
    let double = Scalar::from(2u64);
    println!("double: {:#?}", double * RISTRETTO_BASEPOINT_POINT);
    println!("sum: {:#?}", RISTRETTO_BASEPOINT_POINT + RISTRETTO_BASEPOINT_POINT);
    assert_eq!(double * RISTRETTO_BASEPOINT_POINT, RISTRETTO_BASEPOINT_POINT + RISTRETTO_BASEPOINT_POINT);
}
```
The assert passes, however the prints are different. Why is this and how can I convert one representation to/from another? Thanks!

**Comment by hdevalence** [comment]
Yup, these are two equivalent points. Points can have multiple internal representations, but the debug output prints all the details on the principle that debug output shouldn't hide internal details. You don't need to convert one representation to another, because the API takes care of everything for you.
