### ISSUE TITLE
[Question] Transforming an Edwards point into a Ristretto Point.

### ISSUE THREAD

**Issue by brunoffranca** [dalek-cryptography/curve25519-dalek#329]
My current system uses EdDSA on the Ed25519 curve. I am now changing it to Schnorr on the Ristretto 25519 curve. However, I would like to let my users keep using their old private keys on the new system. Is there a safe way for me to transform their public keys from Ed25519 to Ristretto 25519?

**Comment by tarcieri** [comment]
There is not a well-defined map from Ed(wards)25519 points to Ristretto group elements. The safest option is to rekey.

**Comment by kayabaNerve** [comment]
I hate to comment on an old issue, yet I did want to ask a question and I figured asking here would be less annoying than creating a new issue. Happy to move over.

Isn't an Ed25519 point -> Ristretto point extremely feasible as demonstrated by the basepoint being the same across both curves? Does that property solely apply to the basepoint? Is there something I'm missing? Is there just commentary about how the points can/cannot be used once converted?

https://github.com/dalek-cryptography/curve25519-dalek/blob/main/src/constants.rs#L76 for reference.

I recently needed an alternate basepoint, and had one for Ed25519 which I converted to Ristretto using the same process as above. Would love to hear if my work is no longer secure/proper because of that.

**Comment by burdges** [comment]
If you convert between Ed25519 and Ristretto via `unsafe { transmute::<..>(..) }`, then another Ristretto implementation might convert differently because Ristretto intentionally does not define which branch of the inverse square root they use.  It's fine if you spell out your basepoint manually and forget how you derived it.

**Comment by kayabaNerve** [comment]
Interesting. I took the constant generated from dalek and am using that, so sounds like I'll be good. I didn't forgot about derivation though, instead adding a note about how it was generated so it's verifiable (yet I understand this specific version of dalek may be required depending on the implementation diverges in the future). Shouldn't be an issue as long as other people don't try to redo what I did in practice. Thanks for the info and confirmation!
