### ISSUE TITLE
Implementing Hash for RistrettoPoint (and EdwardsPoint?)

### ISSUE THREAD

**Issue by eleanor-em** [dalek-cryptography/curve25519-dalek#343]
I've just noticed that while `RistrettoPoint` does not implement `Hash`, `CompressedRistretto` does. Is there a particular reason for this that I've missed? It would be pretty easy to write a quick impl that compresses the point and uses the derived hash trait.

(edit: or if it works out to be faster, just hashing the internal representation)

**Comment by burdges** [comment]
You cannot hash the internal representation because projective coordinates violate the rule [`k1 == k2 -> hash(k1) == hash(k2)`](https://doc.rust-lang.org/std/hash/trait.Hash.html#hash-and-eq)

Anything mildly costly should be explicit, which includes point compression.  And point compression should even be batched whenever possible, ala [`double_and_compress_batch`](https://doc.dalek.rs/curve25519_dalek/ristretto/struct.RistrettoPoint.html#method.double_and_compress_batch).

**Comment by eleanor-em** [comment]
Thanks! That makes perfect sense. So: the idea then is the user should explicitly compress the point and let the derived `Hash` take care of the rest.
