### ISSUE TITLE
Potential problem with wording on `Scalar`

### ISSUE THREAD

**Issue by dingxiangfei2009** [dalek-cryptography/curve25519-dalek#356]
cf. https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/scalar.rs#L194

From various tests, I believe `Scalar` actually has the full group order instead of just the prime order `\ell`. For Ed25519 curve, it should be `8 \ell`, including that co-factor `8`. I propose to change the wording to reflect this fact.

**Comment by AnomalRoil** [comment]
This actually seems fine to me: the *arithmetic* on the scalar is done modulo ℓ, but it is possible to construct scalars that are not in their "canonical" form, i.e. not (yet) reduced modulo ℓ, which is probably why your tests lead you to think this is not correct.

If you look at the line above 194, you'll see that it says it can hold "an integer s < 2^255":
https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/scalar.rs#L193-L194
but it **represents** an element of ℤ/ℓ, to have its "canonical representation" you can just reduce it modulo ℓ, but you can still perform arithmetic using the non-canonical representation and when you reduce the outputs, you'll obtain the same "resulting element" in ℤ/ℓ. And actually the outputs will be reduced already if you use the Scalar methods.

See:
https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/scalar.rs#L16-L24

and also:
https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/scalar.rs#L114-L119

So, in order to be "compatible" with Ed25519 / X25519, because of their bit-clamping, Scalars are not necessarily reduced, but while it is possible to construct Scalars that are not canonical, i.e. not reduced, using for example:
https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/scalar.rs#L251-L262
as soon as you are performing arithmetic operations with the Scalars (what it says on line 24 above), you'll get output Scalars that are reduced, see for example:
https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/scalar.rs#L344-L359

Unless you're actually saying that you've tried working with an element "outside of the prime order group" and it "worked"?
This is because of the said reductions above: if you're working with a scalar that is an integer s < 2^255, you're actually working with a scalar in the group ℤ/ℓ  that is not in its canonical form, but it still *represents* a scalar in that prime order group.

It's important to keep in mind we are working here with the **scalars**, not with the elements of an elliptic curve. 

So if you have an elliptic curve defined over a given field, and that elliptic curve has a number of elements, its order, equal to n, when we're *using* that elliptic curve we're typically picking a basepoint B, which will generate a cyclic (sub)group of the elliptic curve (take B, 2B, 3B, etc. until it "wraps" back to B). 
In certain cases, that (sub)group has the same order r as the elliptic curve, but in some cases we have a smaller subgroup, whose order ℓ (the number of elements in that subgroup) will be a divider of the elliptic curve order n. And that's where the cofactor "appears": h = n/ℓ. (This is known as Lagrange's theorem)
Problem can arise when we are working on a point that is not generated by that basepoint B, i.e. using a point in another subgroup of our elliptic curve.

But on the scalar side we do not have this problem: if the scalars are defined over ℤ/ℓ, it just means all operations on scalars will map to scalars in ℤ/ℓ and that scalars are represented in ℤ/ℓ. Which I believe is the case here.

**Comment by dingxiangfei2009** [comment]
@AnomalRoil I see. Yes, looks like I am using non-canonical representation of scalars in those tests. Do you also imply that one should uses points in the prime order group of order ℓ when dealing with arithmetics between `Scalar` and `EdwardsPoint`? I am looking for possible ways to use points in the small torsion group and see if constructing `EdwardsPoint` only with `constants::ED25519_BASE_POINT` avoids that.
