### ISSUE TITLE
Basepoint order constant violates Scalar constraints

### ISSUE THREAD

**Issue by survived** [dalek-cryptography/curve25519-dalek#360]
Documentation claims that Scalar type represents an integer mod the group order. However, BASEPOINT_ORDER constant violates this constraint and construct a scalar = group order. 

Basically, it means that there are 2 different representations of zero scalar: in arithmetic they can be used interchangeably (e.g. `Scalar::one() + Scalar::zero() == Scalar::one() + BASEPOINT_ORDER`), but equality check shows that they are different (i.e. `Scalar::zero() != BASEPOINT_ORDER`).

Consider any function that takes a scalar, tests it agains zero scalar, and proceeds only if it's nonzero:

```rust
fn invert(s: Scalar) -> Option<Scalar> {
    if s == Scalar::zero() {
        None
    } else {
        Some(s.invert())
    }
}
```

`s = BASEPOINT_ORDER` violates invariant of this function, and causes a panic. However it's highly unlikely to get s = group order as it can only be constructed via the constant above

**Comment by AnomalRoil** [comment]
That's a really good point. 
It is caused by the fact that the Scalar type can hold so-called "non-canonical" scalars. (See also [this comment](https://github.com/dalek-cryptography/curve25519-dalek/issues/356#issuecomment-853715598) for more on the topic.)

Notice that all multiples of the `BASEPOINT_ORDER` value that are smaller than 2^255 will also cause the same issue if they are instantiated using [`from_bits`](https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/scalar.rs#L251-L263) for example, so that's actually 7 values that are non-invertible and yet not easily caught as per your POC code.
So there is actually more than just one way to get such an invalid scalar.

I'm not sure what's the best fix:
- simply adding some documentation to the `invert` function saying it requires an integer in canonical form to ensure it's non-zero? 
- add a `is_canonical` check and reduce the Scalar if not in [the equality tests](https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/scalar.rs#L271-L282)? That seems like a performance hit. I'd say it wouldn't be a good idea as it seems we are expecting the current behaviour and thus it might be breaking: https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/scalar.rs#L124-L140
- add a `is_zero` method that's performing the reduction before the comparison and advocating for its use in the documentation of the `invert` function while also adding the said warning about the existence of non-canonical zero values?

I'd lean on either the 1st or 3rd option on my side. I'm happy to send a PR either way if it can help.

**Comment by survived** [comment]
Ah I missed that scalar might be in not canonical form. Thanks, @AnomalRoil! I guess then the above function `invert` should either reduce given `s` or state that `s` must be in canonical form.

I feel like `Scalar` containing integer ≥ group order is something illegal, and in order "to make illegal states unrepresentable", `Scalar` should have been restricted to be < group order. However, current behaviour is probably used many times internally, and not a subject to change

**Comment by isislovecruft** [comment]
Hi @survived! Apologies for the confusion. As @AnomalRoil mentioned, due to backwards compatibility reasons with protocols like x25519 and ed25519, we need to allow scalars to be constructed from arbitrary bit patterns representing up to 2^255 (as much as we'd love to not have to do this).
