### ISSUE TITLE
Finish Ristretto implementation

### ISSUE THREAD

**Issue by isislovecruft** [dalek-cryptography/curve25519-dalek#76]

**Comment by hdevalence** [comment]
I have work in progress on this issue in the following branch: https://github.com/chain/curve25519-dalek/tree/feature/ristretto_r1

**Comment by isislovecruft** [comment]
Some notes are here: https://github.com/isislovecruft/ristretto-paper and I'll update that at some point with more equations and implementation details for Ristretto-based generalised Schnorr signatures.

**Comment by zmanian** [comment]
Ristretto paper paper is still private.

**Comment by hdevalence** [comment]
The PDF notes got subsumed into the Rustdoc notes, since HTML docs are more accessible and live with the implementation.

After #124 is merged, I think the remaining things to document are:

- [ ] more motivation, why multiplying by the cofactor or whatever isn't sufficient for complex protocols, and why there's a problem for basic cases (e.g. according to the Ed25519 paper and RFC, the set of valid signatures is undefined)
- [ ] equality checking
- [ ] elligator
- [ ] the batched double-and-encode function

**Comment by hdevalence** [comment]
Note: a bunch of the work above has moved to the Ristretto website.

**Comment by isislovecruft** [comment]
I'm going to call this done? We have a couple remaining points for this in #148 but the remainder has since moved to https://github.com/Ristretto/website/.

**Comment by isislovecruft** [comment]
Done now, I think?

**Comment by hdevalence** [comment]
Yep!
