### ISSUE TITLE
Improve our #brand

### ISSUE THREAD

**Issue by isislovecruft** [dalek-cryptography/curve25519-dalek#89]
Okay, so, bear with me, as this might seem frivolous (and it is): we should have a logo for *-dalek stuff. I'm thinking a simplified line drawing of a dalek with edwards curves as sparkles coming out of its radar-schnozzley blaster thingies.

Anyone have any better ideas?

**Comment by zmanian** [comment]
We also have a domain name and want content for the website.

**Comment by isislovecruft** [comment]
alors voilà, de rien

![dalek-logo-draft-small](https://user-images.githubusercontent.com/907241/33342331-a7b043f0-d479-11e7-94dc-571bdaad2bbc.JPG)

**Comment by isislovecruft** [comment]
> We also have a domain name and want content for the website.

For ristretto or for dalek stuff in general?

**Comment by zmanian** [comment]
For Ristretto. Happy to get a Dalek Domain name. Not sure how you want to have the brands relate.

Endorse logo.

**Comment by isislovecruft** [comment]
Not sure about brand relation… my vague intuition is to keep them related but separate, though I don't really care either way. Maybe @hdevalence has opinions?

The dalek.rs domain should be pointed at one of my servers in a couple hours, but it can point anywhere. One thing was that @hdevalence wanted separate documentation for people who want to use our API and people who want to read the write ups of what the code is doing internally, what curve models we use, how we do various conversions and operations, etc.

**Comment by hdevalence** [comment]
Yeah, as @isislovecruft said, basically I would like to have two sets of documentation, one that's about the external API, and the other which works as implementation notes.  For instance, the Ristretto notes currently at https://docs.rs/curve25519-dalek/0.13.2/curve25519_dalek/ristretto/index.html are totally unhelpful for people who want to look up how to use the API or just know what Ristretto is. But they should exist in a linkable form, somewhere.

My sense is that the cleanest way to do this is to arrange the Rustdoc so that the public items have documentation just on the API, and the private items have the implementation notes.  Doing this requires hosting our own docs, since docs.rs isn't really set up for that use-case, or for things like "there's a bug in cargo that we can temporarily work around until it's fixed by commenting something out before building the docs".

I would suggest using Cloudfront since it's fast and low-cost. I used https://github.com/laurilehmijoki/s3_website to automate managing the CDN.

**Comment by zmanian** [comment]
I really like the Travis to Firebase we have for ristretto.group. Google manages all the SSL for you.

**Comment by tarcieri** [comment]
Here's an image trace as an SVG, and a PNG re-rasterization:

http://svgur.com/s/4ux

![dalek](https://user-images.githubusercontent.com/797/34898472-83686016-f7f3-11e7-967b-24b2aadd623a.png)

**Comment by isislovecruft** [comment]
If anyone has more ideas feel free to reopen.
